# Generated by Django 6.0.3 on 2026-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_status',
            field=models.CharField(choices=[('none', 'No License'), ('valid', 'Valid License'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
