# Generated by Django 6.0.3 on 2026-03-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='phone_number',
        ),
    ]
